language: "node_js"
node_js: "8"

script:
  - npm run test
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  repo: NadiaPOI/Puissance4
  target_branch: gh-pages
  on:
    branch: master
